/* ============================================================
   AETHERIA — Mapas del mundo
   Leyenda de tiles: ver LEGEND. Objetos/NPCs/portales aparte.
   TODAS las filas de cada mapa tienen exactamente el mismo ancho.
   ============================================================ */
'use strict';

const LEGEND = {
  '.': 'grass1', ',': 'grass2', ';': 'grass_fl1', ':': 'grass_tu1', "'": 'grass_fl2',
  'd': 'dirt1', 'D': 'dirt2', 'c': 'cobble1', 'C': 'cobble_plaza', 'k': 'cobble_c',
  'w': 'water1', 'W': 'water2', '-': 'water_n', '+': 'water_s', '(':'water_w', ')':'water_e',
  '1': 'water_nw', '2': 'water_ne', '3': 'water_sw', '4': 'water_se',
  'b': 'bridge_h',
  'f': 'forest_floor', 'F': 'forest_floor2',
  '#': 'cave_wall', '"': 'cave_wall2', '_': 'cave_floor', '=': 'cave_floor2', '%': 'cave_lava', '&': 'crystal_blue',
  'S': 'wall_stone', 's': 'wall_stone3', 'g': 'floor_gold', 'G': 'floor_dark', 'R': 'carpet_a', 'r': 'carpet_b', 'y': 'carpet_c',
  'P': 'wood_floor', 'p': 'int_wall', 'B': 'int_wall2', 'o': 'wood_floor2',
  'x': 'void',
};

/* Tiles no caminables */
const SOLID_TILES = new Set(['w','W','-','+','(',')','1','2','3','4','#','"','S','s','p','B','x','%']);

/* ============================ MAPAS ============================ */
const MAPS = {

/* ---------- ALDEA DE LUMINA (34x22) ---------- */
village: {
  name: 'Aldea de Lumina', music: 'village', enc: null, bb: 'bb_field',
  rows: [
    "..................................",
    "................dddd..............",
    "..........dddddddddddd............",
    "..........dccccccccccdd...........",
    "....;;....dccccccccccdd.....;;....",
    "...:;;;...dccccccccccdd...:;;;,...",
    "...:;;;,..dccccCCcccdd....:;;;,...",
    "....,,...ddcccCCCCcdd......,,.....",
    ".dddddddddcccCCCCCcdddddddddddd...",
    ".dcccccccccccccccccccccccccccd....",
    ".dcccccccccccccccccccccccccccd....",
    ".ddcccccdddddcccccddddddcccccdd...",
    "..ddcccd....dccccd......dcccdd....",
    "..ddcccd....dccccd......dcccdd....",
    "..dccccd....dccccd......dccccd....",
    "..dccccd....dccccd......dccccd....",
    "...dddd......dddd........dddd.....",
    "...11111..................ddddd...",
    "..(wwwww).................ddddd...",
    "..(wwwww)..................dddd...",
    "...33333..........................",
    "..................................",
  ],
  objects: [
    { type:'house', sprite:'house_inn',    x:4,  y:1, w:5, h:4, door:{x:6, y:5} },
    { type:'house', sprite:'house_shop',   x:18, y:1, w:4, h:4, door:{x:20, y:5} },
    { type:'house', sprite:'house_temple', x:24, y:7, w:5, h:5, door:{x:26, y:12} },
    { type:'house', sprite:'house_red_s',  x:8,  y:11, w:3, h:4 },
    { type:'house', sprite:'house_teal_s', x:12, y:11, w:3, h:4 },
    { type:'house', sprite:'house_green_m',x:21, y:11, w:4, h:4, door:{x:22, y:15} },
    { type:'well',  x:15, y:4 },
    { type:'sign',  x:14, y:8, text:'← Posada del Dragón Dorado   |   Bazar del Aventurero ↓   |   Camino Real ↑' },
    { type:'sign',  x:27, y:12, text:'Templo de Aetheria →' },
    { type:'sign',  x:9,  y:15, text:'Casa de Tia. «Si no huele a estofado, no molestes.»' },
    { type:'sign',  x:13, y:15, text:'Casa de Grom el leñador. Ahora mismo está en la plaza… o en el bosque.' },
    { type:'sign',  x:16, y:6, text:'Pozo de Lumina — ¿quién sabe qué duerme bajo el agua? (Z para bajar)' },
    { type:'tree',  sprite:'prop_tree_oak', x:2,  y:6 }, { type:'tree', sprite:'prop_tree_pine', x:31, y:2 },
    { type:'tree',  sprite:'prop_tree_pine', x:0, y:14 }, { type:'tree', sprite:'prop_tree_oak', x:32, y:16 },
    { type:'tree',  sprite:'prop_tree_autumn', x:16, y:16 }, { type:'tree', sprite:'prop_tree_small', x:11, y:9 },
    { type:'tree',  sprite:'prop_tree_small', x:25, y:2 },
  ],
  portals: [
    { x:6,  y:5,  to:'inn',    tx:7, ty:4,  door:true },
    { x:20, y:5,  to:'shopA',  tx:5, ty:3,  door:true },
    { x:22, y:15, to:'shopB',  tx:5, ty:3,  door:true },
    { x:26, y:12, to:'temple', tx:7, ty:7,  door:true },
    { x:16, y:0, to:'road',   tx:1, ty:15 }, { x:17, y:0, to:'road', tx:2, ty:15 },
    { x:0, y:9, to:'road', tx:24, ty:8 }, { x:0, y:10, to:'road', tx:24, ty:8 },
  ],
  chests: [
    { x:3, y:16, item:'potion', qty:2 },
    { x:30, y:14, gold:80 },
  ],
  triggers: [
    { x:24, y:12, w:5, h:2, event:'firstEnterVillage', once:true, cond:'gameStarted' },
    { x:15, y:1, w:4, h:1, event:'firstEnterVillage', once:true, cond:'gameStarted' },
    { x:31, y:9, w:2, h:1, event:'firstEnterVillage', once:true, cond:'gameStarted' },
  ],
  npcs: [
    { id:'elder', name:'Alcalde Bram', x:14, y:6, face:'face_elder_m', walk:['walk_m_townfolk',4], wander:true,
      talk:[
        { cond:'!metElder', say:['¡Oh! ¿Eres TÚ el héroe invocado que anunció la sacerdotisa?','Soy Bram, alcalde de Lumina. Esta aldea vive del bosque... pero algo oscuro lo corrompe.','Si planeas encarar al Rey Demonio Vorthak, necesitarás aliados. Elowen, la maga élfica, estudia junto al pozo... y busca a Kira en el bosque: es nuestra mejor espadachina.'], set:'metElder' },
        { cond:'!slimeQuestDone', say:['Los monstruos del Camino Real se vuelven agresivos. Derrota a 3 grupos y te recompensaré.'], quest:'slimes' },
        { cond:'slimeQuestDone&&!slimeClaimed', say:['¡Increíble! Los caminos vuelven a ser seguros. Toma esto: 150 de oro y una Mega Poción.'], giveGold:150, giveItem:['hipotion',1], set:'slimeClaimed', complete:'slimes', sfx:'chest' },
        { cond:'bossFinalDown', say:['¡El cielo se abrió! Vorthak ha caído. Lumina no olvidará tu nombre, héroe.'] },
        { cond:'bossCaptainDown', say:['Mordrax ya no bloquea el trono. El Nudo Sombrío te espera... y el pueblo reza.'] },
        { cond:'bossGolemDown', say:['Las cavernas callaron. Solo queda la Fortaleza. Descansa si puedes.'] },
        { cond:'bossSpiderDown', say:['Kira dice que la araña cayó. El bosque respira... pero las cavernas siguen rugiendo.'] },
        { say:['El Rey Demonio aguarda en su Fortaleza, tras las Cavernas de Cristal al este.','Que la luz de Aetheria te guíe, héroe.'] },
      ] },
    { id:'kid', name:'Nino', x:11, y:7, face:'face_child_f', walk:['walk_f_townfolk',5], wander:true,
      talk:[ { cond:'?q_flower', say:['¡¡WOW!! ¡¿Es para mí?! ¡Una Flor de Aurora de verdad!','¡Gracias, héroe! ¡Eres el mejor! Toma, te doy todos mis ahorros.'], removeItem:'q_flower', giveGold:100, giveItem:['potion',1], set:'flowerTurned', complete:'flower', sfx:'chest' },
             { cond:'!flowerTurned', say:['¡Wiii! ¿De verdad viniste de OTRO mundo?','Si me traes una Flor de Aurora del bosque te doy un premio. ¡Prometido!'], quest:'flower' },
             { say:['¡La flor huele riquísimo! La guardaré para siempre.'] } ] },
    { id:'elowen', name:'Elowen', x:20, y:8, face:'face_magician_f', walk:['walk_f_magician',0], wander:false, hiddenUntil:'metElder',
      talk:[ { cond:'!elowenJoined', say:['...Siento que tu aura resuena con el círculo de invocación. Tú eres el Invocado, ¿verdad?','Soy Elowen, maga élfica del templo. El bosque susurra con magia corrupta...','Mi magia ardiente arderá en tus filas. No acepto un no como respuesta.'], join:'elowen', set:'elowenJoined', after:'hide:elowen' },
             { say:['La Viuda Carmesí y los limos temen el FUEGO. Recuérdalo cuando lances mis hechizos.','Estudia, ama la magia... y quema a los malvados.'] } ] },
    { id:'villager1', name:'Aldeana Tia', x:8, y:9, face:'face_young2_f', walk:['walk_f_townfolk',2], wander:true,
      talk:[
        { cond:'bossFinalDown', say:['¡Volviste! El estofado de hoy es de fiesta. Siéntate, héroe, te lo has ganado.'] },
        { cond:'bossSpiderDown', say:['El bosque ya no cruje de noche. Gracias... de verdad.'] },
        { say:['La posada del Dragón Dorado restaura todas tus fuerzas por 20 de oro.','Dicen que su estofado es capaz de revivir a un héroe caído. Ja, ja.'] },
      ] },
    { id:'villager2', name:'Leñador Grom', x:29, y:15, face:'face_berserk_m', walk:['walk_m_townfolk',0], wander:false,
      talk:[ { cond:'!metGrom', say:['¡Cuidado en el bosque, forastero! Unas arañas GIGANTES se adueñaron del claro este.','Dicen que su telaraña detiene hasta a un oso.'], set:'metGrom' },
             { say:['Los lobos del bosque cazan en manadas. No te confíes.'] } ] },
    { id:'guard', name:'Guardián Ren', x:16, y:2, face:'face_soldier_m', walk:['walk_m_townfolk',3], wander:false,
      talk:[ { say:['El Camino Real al oeste lleva al Bosque de los Susurros.','Más allá: las Cavernas de Cristal y la Fortaleza del Rey Demonio...'] } ] },
  ],
},

/* ---------- CAMINO REAL (26x18) ---------- */
road: {
  name: 'Camino Real', music: 'forest', enc: 'road', rate: 0.09, bb: 'bb_field',
  rows: [
    "..........................",
    "..........................",
    ".....,;;;........d........",
    "....:;;;,..d.....d........",
    "....,,,...ddd....d...ddddd",
    "..........dd.....d...dcccc",
    "..........dd.....ddddddccd",
    "ddddddddddd...dddddd....cd",
    "ccccccccccdddddd......dd.d",
    "dcccccccccc..........dd..d",
    "ddccccccccc..........dd..d",
    "..ddcccccddddddddddddddd..",
    "...dddddd......d..........",
    "..........;;;,..d.........",
    ".........:;;;,..d.........",
    "..........,,....d.........",
    "..........................",
    "..........................",
  ],
  objects: [
    { type:'sign', x:2, y:14, text:'← Aldea de Lumina      Bosque de los Susurros →' },
    { type:'tree', sprite:'prop_tree_oak', x:7, y:2 }, { type:'tree', sprite:'prop_tree_pine', x:20, y:4 },
    { type:'tree', sprite:'prop_tree_autumn', x:14, y:12 }, { type:'tree', sprite:'prop_tree_oak', x:23, y:1 },
    { type:'tree', sprite:'prop_tree_small', x:10, y:5 }, { type:'tree', sprite:'prop_tree_small', x:5, y:12 },
  ],
  portals: [
    { x:25, y:5, to:'village', tx:1, ty:10 },
    { x:0, y:8, to:'village', tx:32, ty:9 }, { x:0, y:9, to:'village', tx:32, ty:9 }, { x:0, y:10, to:'village', tx:32, ty:9 },
    { x:25, y:7, to:'forest', tx:2, ty:12 }, { x:25, y:8, to:'forest', tx:2, ty:12 },
  ],
  chests: [ { x:21, y:3, item:'herb', qty:2 } ],
  npcs: [],
},

/* ---------- BOSQUE DE LOS SUSURROS (34x19) ---------- */
forest: {
  name: 'Bosque de los Susurros', music: 'forest', enc: 'forest', rate: 0.11, bb: 'bb_forest',
  rows: [
    "ffffffffffffffffffffffffffffffffff",
    "fffffffffffffFFffffffffffFFfffffff",
    "fffFFffffffffffffffffffFFfffffFFFf",
    "ffffffffffffFFfffffFFFFFFFFfffffff",
    "ffffFFfffffffffffffffffffFFffffffF",
    "fffffffffffffFFFFFFfffffffffffffff",
    "fffFFfffffffffffffffffFFFFFfffffff",
    "fffffffffFFFFffffffFFfffffffffffff",
    "ffFFFFffffffffffffffffffffffffffff",
    "fffffffffffFFffFFFFfffFFFfffffffff",
    "fffFFffffffffffffffffffffFFFFFFfff",
    "fffffffffffffffffffffFFFffffffffff",
    "ffffFFFFFFfffFFfffffffffffffffffff",
    "fffffffffffffffffffFFffFFFFfffffff",
    "ffFFFFffffffFFffffffffffffffffffff",
    "ffffffffffffffffFFFFffffffffffffff",
    "fffFFfffffffffffffffffffffFFffffff",
    "ffffFFFFFFffffffffFFFFffffffffffff",
    "ffffffffffffffffffffffffffffffffff",
  ],
  objects: [
    { type:'tree', sprite:'prop_tree_small', x:1, y:0 },
    { type:'tree', sprite:'prop_tree_pine', x:7, y:0 },
    { type:'tree', sprite:'prop_tree_small', x:9, y:0 },
    { type:'tree', sprite:'prop_tree_oak', x:12, y:0 },
    { type:'tree', sprite:'prop_tree_pine', x:19, y:0 },
    { type:'tree', sprite:'prop_tree_pine', x:23, y:0 },
    { type:'tree', sprite:'prop_tree_autumn', x:26, y:0 },
    { type:'tree', sprite:'prop_tree_pine', x:27, y:0 },
    { type:'tree', sprite:'prop_tree_autumn', x:7, y:1 },
    { type:'tree', sprite:'prop_tree_small', x:10, y:1 },
    { type:'tree', sprite:'prop_tree_pine', x:12, y:1 },
    { type:'tree', sprite:'prop_tree_pine', x:24, y:1 },
    { type:'tree', sprite:'prop_tree_oak', x:2, y:2 },
    { type:'tree', sprite:'prop_tree_small', x:23, y:2 },
    { type:'tree', sprite:'prop_tree_autumn', x:24, y:2 },
    { type:'tree', sprite:'prop_tree_pine', x:25, y:2 },
    { type:'tree', sprite:'prop_tree_autumn', x:5, y:3 },
    { type:'tree', sprite:'prop_tree_oak', x:11, y:3 },
    { type:'tree', sprite:'prop_tree_small', x:24, y:3 },
    { type:'tree', sprite:'prop_tree_autumn', x:3, y:5 },
    { type:'tree', sprite:'prop_tree_oak', x:9, y:5 },
    { type:'tree', sprite:'prop_tree_autumn', x:23, y:5 },
    { type:'tree', sprite:'prop_tree_small', x:3, y:6 },
    { type:'tree', sprite:'prop_tree_oak', x:10, y:6 },
    { type:'tree', sprite:'prop_tree_pine', x:2, y:7 },
    { type:'tree', sprite:'prop_tree_small', x:1, y:8 },
    { type:'tree', sprite:'prop_tree_pine', x:7, y:8 },
    { type:'tree', sprite:'prop_tree_pine', x:11, y:8 },
    { type:'tree', sprite:'prop_tree_autumn', x:3, y:9 },
    { type:'tree', sprite:'prop_tree_small', x:18, y:9 },
    { type:'tree', sprite:'prop_tree_oak', x:33, y:9 },
    { type:'tree', sprite:'prop_tree_pine', x:1, y:10 },
    { type:'tree', sprite:'prop_tree_autumn', x:12, y:10 },
    { type:'tree', sprite:'prop_tree_oak', x:15, y:11 },
    { type:'tree', sprite:'prop_tree_oak', x:19, y:11 },
    { type:'tree', sprite:'prop_tree_pine', x:26, y:11 },
    { type:'tree', sprite:'prop_tree_autumn', x:6, y:12 },
    { type:'tree', sprite:'prop_tree_autumn', x:14, y:12 },
    { type:'tree', sprite:'prop_tree_pine', x:15, y:12 },
    { type:'tree', sprite:'prop_tree_oak', x:16, y:12 },
    { type:'tree', sprite:'prop_tree_pine', x:27, y:12 },
    { type:'tree', sprite:'prop_tree_autumn', x:30, y:12 },
    { type:'tree', sprite:'prop_tree_autumn', x:11, y:13 },
    { type:'tree', sprite:'prop_tree_pine', x:12, y:13 },
    { type:'tree', sprite:'prop_tree_small', x:18, y:13 },
    { type:'tree', sprite:'prop_tree_autumn', x:19, y:13 },
    { type:'tree', sprite:'prop_tree_autumn', x:27, y:13 },
    { type:'tree', sprite:'prop_tree_pine', x:1, y:14 },
    { type:'tree', sprite:'prop_tree_oak', x:10, y:14 },
    { type:'tree', sprite:'prop_tree_small', x:19, y:14 },
    { type:'tree', sprite:'prop_tree_autumn', x:28, y:14 },
    { type:'tree', sprite:'prop_tree_oak', x:11, y:15 },
    { type:'tree', sprite:'prop_tree_small', x:16, y:15 },
    { type:'tree', sprite:'prop_tree_pine', x:26, y:15 },
    { type:'tree', sprite:'prop_tree_autumn', x:2, y:16 },
    { type:'tree', sprite:'prop_tree_oak', x:24, y:16 },
    { type:'tree', sprite:'prop_tree_pine', x:4, y:17 },
    { type:'tree', sprite:'prop_tree_oak', x:5, y:17 },
    { type:'tree', sprite:'prop_tree_oak', x:17, y:17 },
    { type:'tree', sprite:'prop_tree_oak', x:21, y:17 },
    { type:'tree', sprite:'prop_tree_oak', x:29, y:17 },
    { type:'tree', sprite:'prop_tree_pine', x:1, y:18 },
    { type:'tree', sprite:'prop_tree_oak', x:6, y:18 },
    { type:'canopy', x:5, y:3 }, { type:'canopy', x:13, y:6 }, { type:'canopy', x:21, y:3 },
    { type:'canopy', x:28, y:12 }, { type:'canopy', x:10, y:16 },
    { type:'mushroom', x:7, y:15 }, { type:'mushroom', x:20, y:12 }, { type:'mushroom', x:29, y:10 },
    { type:'sign', x:3, y:11, text:'Bosque de los Susurros — Cuidado: arañas gigantes al este' },
  ],
  portals: [
    { x:0, y:12, to:'road', tx:24, ty:8 }, { x:0, y:13, to:'road', tx:24, ty:8 },
    { x:33, y:5, to:'cave', tx:2, ty:14 }, { x:33, y:6, to:'cave', tx:2, ty:14 },
  ],
  chests: [
    { x:29, y:2, item:'w_iron' },
    { x:8, y:17, gold:120 },
    { x:31, y:16, item:'q_flower' },
    { x:17, y:3, item:'q_relic' },
  ],
  triggers: [
    { x:32, y:3, w:2, h:5, boss:'bossSpider', once:true, cond:'!bossSpiderDown',
      intro:['¡Las hojas tiemblan! Una figura enorme baja de los árboles...','Viuda Carmesí: Tssss... carne fresca ha entrado en MI bosque...'] },
    { x:28, y:4, w:5, h:5, event:'kiraJoin', once:true, cond:'bossSpiderDown' },
  ],
  npcs: [
    { id:'hunter', name:'Cazador Fael', x:16, y:8, face:'face_ranger_m', walk:['walk_m_ranger',0], wander:false,
      talk:[ { cond:'!metFael', say:['¡Alto ahí! Poco avisado viajero... este bosque ya no es seguro desde que la gran araña anida al este.','Si logras vencerla, la joven Kira te espera con interés... ella intentó cazarla sola.'], set:'metFael' },
             { say:['La Viuda Carmesí es débil al FUEGO. Recuérdalo, viajero.'] } ] },
    { id:'kira', name:'Kira', x:26, y:7, face:'face_warrior_f', walk:['walk_f_warrior',0], wander:false, hiddenUntil:'bossSpiderDown',
      talk:[ { cond:'!kiraJoined', say:['...Así que TÚ eres el héroe invocado. Yo soy Kira.','Intenté vencer a esa araña yo sola y... bueno, aquí sigo. Soy dura de pelar, lo admito.','El Rey Demonio mató a mi padre. Voy contigo, y no es una petición.'], join:'kira', set:'kiraJoined', after:'hide:kira' },
             { say:['¡Ese Vorthak pagará por lo que hizo!','Cuando peleemos, ve con todo. Yo cubro tu espalda.'] } ] },
  ],
},

/* ---------- CAVERNAS DE CRISTAL (30x19) ---------- */
cave: {
  name: 'Cavernas de Cristal', music: 'cave', enc: 'cave', rate: 0.12, bb: 'bb_cave', dark: true,
  rows: [
    "##############################",
    "#####______##########___######",
    "###__________###______####_###",
    "###___&&___%______%__###____##",
    "##_______#####______###_____##",
    "##___%__#######_____##______##",
    "##______##____##____________&#",
    "#_____####_____####___###____#",
    "#_%_____#####____#___#__%____#",
    "#______###___#____#__________#",
    "##_____#_____#____####___####",
    "###____#_____##______#___#___#",
    "####___###_###_______#___#___#",
    "#______#_____#___###_###_#___#",
    "#___%__#_________#_______#___#",
    "##_____####___#__#___###___###",
    "###______#_____#____#______###",
    "#####__________##__________###",
    "######____%_____####____######",
  ],
  objects: [
    { type:'crystal', x:6, y:3 }, { type:'crystal', x:7, y:3 }, { type:'crystal', x:28, y:6 },
    { type:'crystal', x:24, y:4 }, { type:'crystal', x:13, y:6 }, { type:'crystal', x:22, y:2 },
    { type:'crystal', x:12, y:17 }, { type:'crystal', x:20, y:9 },
    { type:'sign', x:13, y:17, text:'Cavernas de Cristal — El eco responde con murmullos fríos...' },
  ],
  portals: [
    { x:1, y:14, to:'forest', tx:32, ty:5 },
    { x:28, y:8, to:'castle', tx:2, ty:10 }, { x:28, y:9, to:'castle', tx:2, ty:10 },
  ],
  chests: [
    { x:22, y:1, item:'a_chain' },
    { x:7, y:18, gold:200 },
    { x:17, y:2, item:'phoenix' },
  ],
  triggers: [
    { x:25, y:7, w:4, h:4, boss:'bossGolem', once:true, cond:'!bossGolemDown',
      intro:['El suelo vibra con pasos pesados... ¡La roca misma se alza!','Gólem de Cristal: INTRUSO. APLASTAR.'] },
  ],
  npcs: [
    { id:'miner', name:'Minero Bruno', x:5, y:12, face:'face_monk_m', walk:['walk_m_townfolk',1], wander:false,
      talk:[ { cond:'!metBruno', say:['¡Por los cristales! ¡Un visitante! Llevo meses atrapado aquí por el Gólem...','El Gólem de Cristal guarda la salida este. Le golpea el TRUENO, pero... buena suerte, viajero.'], set:'metBruno', giveItem:['potion',2] },
             { say:['Estos cristales cantan cuando se acerca un monstruo. Escucha el silencio.'] } ] },
  ],
},

/* ---------- FORTALEZA SOMBRÍA (32x16) ---------- */
castle: {
  name: 'Fortaleza de Vorthak', music: 'castle', enc: 'castle', rate: 0.12, bb: 'bb_castle',
  rows: [
    "SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
    "SGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGS",
    "SGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGS",
    "SGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGS",
    "SGGGGGGGGGRRRRRRRRRRRRGGGGGGGGGS",
    "SGGGGGGGGGrrrrrrrrrrrrGGGGGGGGGS",
    "SGGGGGGGGGRRRRRRRRRRRRGGGGGGGGGS",
    "SGGGGGGGGGrrrrrrrrrrrrGGGGGGGGGS",
    "SGGGGGGGGGRRRRRRRRRRRRGGGGGGGGGS",
    "SGGGGGGGGGrrrrrrrrrrrrGGGGGGGGGS",
    "SGGGGGGGGGRRRRRRRRRRRRGGGGGGGGGS",
    "SGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGS",
    "SGGGGGGGGGGGGRRRRRGGGGGGGGGGGGGS",
    "SGGGGGGGGGGGGRRRRRGGGGGGGGGGGGGS",
    "SGGGGGGGGGGGGRRRRRGGGGGGGGGGGGGS",
    "SSSSSSSSSSSSSSGGGSSSSSSSSSSSSSSS",
  ],
  objects: [
    { type:'torch', x:8, y:2 }, { type:'torch', x:23, y:2 }, { type:'torch', x:8, y:9 },
    { type:'torch', x:23, y:9 }, { type:'torch', x:12, y:11 }, { type:'torch', x:19, y:11 },
    { type:'column', x:10, y:3 }, { type:'column', x:21, y:3 },
    { type:'column', x:10, y:8 }, { type:'column', x:21, y:8 },
    { type:'sign', x:4, y:9, text:'Fortaleza de Vorthak — Todo aquel que entra, se arrodilla o perece.' },
  ],
  portals: [
    { x:1, y:10, to:'cave', tx:27, ty:8 }, { x:1, y:11, to:'cave', tx:27, ty:8 },
    { x:14, y:15, to:'throne', tx:8, ty:8 }, { x:15, y:15, to:'throne', tx:9, ty:8 }, { x:16, y:15, to:'throne', tx:8, ty:8 },
  ],
  chests: [
    { x:29, y:1, item:'w_flame' },
    { x:2, y:1, item:'elixir' },
  ],
  triggers: [
    { x:13, y:12, w:5, h:3, boss:'bossCaptain', once:true, cond:'!bossCaptainDown',
      intro:['Una figura blindada bloquea las puertas del trono.','General Mordrax: El Rey no recibe... ¡PORQUE YO NO LO PERMITO, GUSANO!'] },
  ],
  npcs: [
    { id:'merchant', name:'Mercader Sombrío', x:26, y:6, face:'face_merchant', walk:['walk_m_townfolk',2], wander:false,
      talk:[ { shop:'castleTown', say:['Je, je... un humano con valor (o estupidez). Vendo al mejor postor, sin preguntas.','Mis reliquias son las mejores de Aetheria... si tienes el oro, tengo el poder.'] } ] },
    { id:'prisoner', name:'Prisionero Eln', x:5, y:6, face:'face_pirate', walk:['walk_m_townfolk',2], wander:false,
      talk:[ { cond:'!metEln', say:['¡Shhh! Soy Eln, explorador del reino... me capturaron husmeando aquí.','Vorthak canaliza el poder del Nudo Sombrío en su trono. Necesitarás toda la luz posible...','Toma, me quedé con esto por si moría: un Elixir. Acaba con esto, héroe.'], set:'metEln', giveItem:['elixir',1] },
             { say:['Los soldados temen al General Mordrax... pero Vorthak teme a otra cosa: al Héroe de la Profecía.'] } ] },
  ],
},

/* ---------- SALA DEL TRONO (18x11) ---------- */
throne: {
  name: 'Nudo Sombrío', music: 'boss', enc: 'throne', rate: 0.10, bb: 'bb_castle',
  rows: [
    "SSSSSSSSSSSSSSSSSS",
    "SGGGGGGGGGGGGGGGGS",
    "SGRRRRRRRRRRRRRRGS",
    "SGyyyyyyyyyyyyyyGS",
    "SGyyyyyyyyyyyyyyGS",
    "SGyyyyyyyyyyyyyyGS",
    "SGyyyyyyyyyyyyyyGS",
    "SGRRRRRRRRRRRRRRGS",
    "SGGGGGGGGGGGGGGGGS",
    "SGGGGGGGGGGGGGGGGS",
    "SSSSSSSSSSSSSSSSSS",
  ],
  objects: [
    { type:'torch', x:3, y:1 }, { type:'torch', x:14, y:1 },
    { type:'throne', x:8, y:1 },
  ],
  portals: [
    { x:8, y:9, to:'castle', tx:15, ty:13 }, { x:9, y:9, to:'castle', tx:15, ty:13 },
  ],
  chests: [],
  triggers: [
    { x:1, y:3, w:16, h:1, boss:'bossDragon', once:true, cond:'!bossDragonDown',
      intro:['¡Las sombras se retuercen y un rugido sacude la sala!','Draco Infernal: GRRRAAAAWR... quién osa perturbar el Nudo...'] },
    { x:1, y:6, w:16, h:1, boss:'bossFinal', once:true, cond:'bossDragonDown&&!bossFinalDown',
      intro:['Vorthak: Así que el juguete de los dioses llegó a mi puerta...','Vorthak: ¡MIL MUNDOS he devorado, y el tuyo será un bocadillo tras la cena!','¡El Rey Demonio despliega sus alas de oscuridad!'] },
  ],
  npcs: [],
},

/* ---------- POZO DE LUMINA ---------- */
well: {
  name: 'Pozo de Lumina', music: 'cave', enc: null, bb: 'bb_cave', dark: true,
  rows: [
    "############",
    "#__________#",
    "#__&&______#",
    "#______%___#",
    "#__________#",
    "#____&&____#",
    "#__________#",
    "#__________#",
    "############",
  ],
  objects: [
    { type:'crystal', x:3, y:2 }, { type:'crystal', x:4, y:2 },
    { type:'crystal', x:5, y:5 }, { type:'sign', x:6, y:7, text:'Una escalera de cuerda sube a la plaza. El eco del pueblo se oye lejano.' },
  ],
  portals: [ { x:5, y:7, to:'village', tx:15, ty:6 } ],
  chests: [
    { x:2, y:2, item:'ac_charm' },
    { x:9, y:6, gold:180 },
  ],
  npcs: [],
},

/* ---------- INTERIORES ---------- */
temple: {
  name: 'Templo de Aetheria', music: 'village', enc: null, bb: 'bb_field',
  rows: [
    "pppppppppppppp",
    "BooooooooooooB",
    "BooooooooooooB",
    "BooooooooooooB",
    "BooooooooooooB",
    "BooooooooooooB",
    "BooooooooooooB",
    "BooooooooooooB",
    "BooooooooooooB",
    "pppppppppppppp",
  ],
  objects: [
    { type:'column', x:2, y:1 }, { type:'column', x:6, y:1 }, { type:'column', x:10, y:1 },
    { type:'column', x:2, y:6 }, { type:'column', x:6, y:6 }, { type:'column', x:10, y:6 },
    { type:'altar', x:7, y:1 },
  ],
  portals: [ { x:7, y:8, to:'village', tx:26, ty:13 } ],
  chests: [],
  npcs: [
    { id:'sister', name:'Hermana Mirena', x:4, y:4, face:'face_nun', walk:['walk_f_healer',0], wander:false,
      talk:[ { cond:'!metMirena', say:['Bienvenido al templo, héroe. La Diosa te convocó de otro mundo... su luz te escoltó aquí.','El mal corrompe el mundo desde el Nudo Sombrío. Reza, y prepárate.','Toca el altar del fondo para guardar tu progreso.'], set:'metMirena' },
             { cond:'?q_relic', say:['¡La Reliquia del Templo! Los goblins la robaron del altar... La Diosa te bendiga, héroe.','Acepta 200 de oro como gratitud del templo.'], removeItem:'q_relic', giveGold:200, set:'relicTurned', complete:'relic', sfx:'chest' },
             { cond:'!relicTurned', say:['Los goblins del bosque robaron la Reliquia del Templo...','Si la recuperas, la Diosa (y yo) te recompensaremos.'], quest:'relic' },
             { say:['El mal corrompe el mundo desde el Nudo Sombrío. Reza, y prepárate.','Toca el altar del fondo para guardar tu progreso.'] } ] },
    { id:'fina', name:'Fina', x:10, y:4, face:'face_nun', walk:['walk_f_healer',3], wander:false, hiddenUntil:'bossSpiderDown',
      talk:[ { cond:'!finaJoined', say:['¡Has vuelto! Lo sentí a través de la luz: has vencido a la araña del bosque.','Soy Fina, aprendiza de la Hermana Mirena. Tras tener una visión... sé que mi lugar es a tu lado.','Mis curaciones protegerán al grupo. ¡Vamos!'], join:'fina', set:'finaJoined', after:'hide:fina' },
             { say:['Que la luz de Lumina te acompañe siempre.','Si alguien cae en combate, yo lo levantaré. Palabra de clériga.'] } ] },
  ],
},

inn: {
  name: 'Posada del Dragón Dorado', music: 'village', enc: null, bb: 'bb_field',
  rows: [
    "pppppppppppppp",
    "PooooooooooooP",
    "PooooooooooooP",
    "PooooooooooooP",
    "PooooooooooooP",
    "PooooooooooooP",
    "pppppppppppppp",
  ],
  objects: [
    { type:'bed', x:1, y:2 }, { type:'bed', x:1, y:4 },
    { type:'table', x:8, y:2 }, { type:'table', x:8, y:4 },
    { type:'counter', x:11, y:2 }, { type:'pot', x:12, y:1 },
  ],
  portals: [ { x:7, y:5, to:'village', tx:6, ty:6 } ],
  chests: [],
  npcs: [
    { id:'innkeeper', name:'Doña Rosa', x:10, y:2, face:'face_dancer_f', walk:['walk_f_townfolk',3], wander:false,
      talk:[ { inn:20, say:['¡Bienvenido al Dragón Dorado! 20 de oro por una noche y sales con las botas repulpidas. ¿Una habitación?'] },
             { say:['Descansa cuando quieras, cielo. El estofado siempre está caliente.'] } ] },
    { id:'bard', name:'Bardo Lirón', x:4, y:3, face:'face_bard_f', walk:['walk_m_townfolk',5], wander:false,
      talk:[ { cond:'!metBard', say:['♪ "Y el héroe bajó del cielo, con la espada de la luz..."','¡Ja! Así empieza TU canción, forastero. El resto... lo escribes tú.'], set:'metBard' },
             { say:['Dicen que en las profundidades de las cavernas hay cristales que susurran secretos...'] } ] },
  ],
},

shopA: {
  name: 'Tienda de Mira', music: 'village', enc: null, bb: 'bb_field',
  rows: [
    "pppppppppp",
    "PooooooooP",
    "PooooooooP",
    "PooooooooP",
    "PooooooooP",
    "pppppppppp",
  ],
  objects: [
    { type:'counter', x:3, y:1 }, { type:'counter', x:4, y:1 }, { type:'counter', x:5, y:1 },
    { type:'pot', x:8, y:1 }, { type:'pot', x:1, y:4 },
  ],
  portals: [ { x:5, y:4, to:'village', tx:20, ty:6 } ],
  chests: [],
  npcs: [
    { id:'mira', name:'Mira', x:4, y:2, face:'face_merchant', walk:['walk_f_townfolk',0], wander:false,
      talk:[ { shop:'village', say:['¡Pociones frescas, hojas recién afiladas! ¿Qué necesitas, héroe?'] } ] },
    { id:'client', name:'Viajero', x:7, y:3, face:'face_young2_m', walk:['walk_m_townfolk',2], wander:false,
      talk:[ { say:['Compré una Espada de Hierro aquí. ¡En el Bazar del Aventurero (la casa verde) venden cosas aún mejores!','...cuando alguien se atreva a llegar hasta Vorthak, claro.'] } ] },
  ],
},

shopB: {
  name: 'Bazar del Aventurero', music: 'village', enc: null, bb: 'bb_field',
  rows: [
    "pppppppppp",
    "PooooooooP",
    "PooooooooP",
    "PooooooooP",
    "PooooooooP",
    "pppppppppp",
  ],
  objects: [
    { type:'counter', x:3, y:1 }, { type:'counter', x:4, y:1 }, { type:'counter', x:5, y:1 },
    { type:'pot', x:8, y:1 }, { type:'pot', x:1, y:4 },
  ],
  portals: [ { x:5, y:4, to:'village', tx:22, ty:16 } ],
  chests: [],
  npcs: [
    { id:'otto', name:'Otto el Bazarero', x:4, y:2, face:'face_merchant', walk:['walk_m_townfolk',4], wander:false,
      talk:[ { shop:'village2', say:['¡Bienvenido al Bazar, donde los héroes de verdad se equipan! Metal de hierro, plumas de fénix...','Gasta con confianza: cuanto más oscuro es el mundo, más vale el buen acero.'] } ] },
    { id:'guardB', name:'Guardia Arin', x:7, y:3, face:'face_soldier_m', walk:['walk_m_townfolk',3], wander:false,
      talk:[ { say:['Escuché que las Cavernas de Cristal guardan un Gólem. Le golpea el trueno...','Y que en la fortaleza del Rey Demonio un mercader sombrío vende reliquias a quien pague. ¡Qué falta me hace ese oro!'] } ] },
  ],
},
};
